onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /sch_arbiter_tb/clk
add wave -noupdate /sch_arbiter_tb/rst_n
add wave -noupdate /sch_arbiter_tb/valid
add wave -noupdate /sch_arbiter_tb/data
add wave -noupdate /sch_arbiter_tb/valid_fifo_sch
add wave -noupdate /sch_arbiter_tb/dq_i
add wave -noupdate /sch_arbiter_tb/idx_i
add wave -noupdate /sch_arbiter_tb/ra_i
add wave -noupdate /sch_arbiter_tb/ca_i
add wave -noupdate /sch_arbiter_tb/t_i
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/FIFO_REGISTERS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/FIFO_REGISTERS}
add wave -noupdate /sch_arbiter_tb/BankScheduler/pop
add wave -noupdate /sch_arbiter_tb/BankScheduler/selector/push
add wave -noupdate /sch_arbiter_tb/BankScheduler/scheduler/CS
add wave -noupdate /sch_arbiter_tb/BankScheduler/scheduler/NS
add wave -noupdate /sch_arbiter_tb/cntr_mode/CS
add wave -noupdate /sch_arbiter_tb/cntr_mode/NS
add wave -noupdate /sch_arbiter_tb/grant_sch_fifo
add wave -noupdate /sch_arbiter_tb/ready
add wave -noupdate /sch_arbiter_tb/valid_sch_arbiter
add wave -noupdate /sch_arbiter_tb/dq_sch_arb
add wave -noupdate /sch_arbiter_tb/idx_sch_arb
add wave -noupdate /sch_arbiter_tb/ra_sch_arb
add wave -noupdate /sch_arbiter_tb/ca_sch_arb
add wave -noupdate /sch_arbiter_tb/t_sch_arb
add wave -noupdate /sch_arbiter_tb/rd_empty
add wave -noupdate /sch_arbiter_tb/num
add wave -noupdate /sch_arbiter_tb/dq_o
add wave -noupdate /sch_arbiter_tb/idx_o
add wave -noupdate /sch_arbiter_tb/ra_o
add wave -noupdate /sch_arbiter_tb/ca_o
add wave -noupdate /sch_arbiter_tb/ba_o
add wave -noupdate /sch_arbiter_tb/bg_o
add wave -noupdate /sch_arbiter_tb/t_o
add wave -noupdate /sch_arbiter_tb/mode
add wave -noupdate /sch_arbiter_tb/mapper_fifo/clk
add wave -noupdate /sch_arbiter_tb/mapper_fifo/rst_n
add wave -noupdate /sch_arbiter_tb/mapper_fifo/data_i
add wave -noupdate /sch_arbiter_tb/mapper_fifo/valid_i
add wave -noupdate /sch_arbiter_tb/mapper_fifo/grant_o
add wave -noupdate /sch_arbiter_tb/mapper_fifo/last_addr
add wave -noupdate /sch_arbiter_tb/mapper_fifo/mid
add wave -noupdate /sch_arbiter_tb/mapper_fifo/data_o
add wave -noupdate /sch_arbiter_tb/mapper_fifo/valid_o
add wave -noupdate /sch_arbiter_tb/mapper_fifo/grant_i
add wave -noupdate /sch_arbiter_tb/mapper_fifo/CS
add wave -noupdate /sch_arbiter_tb/mapper_fifo/NS
add wave -noupdate /sch_arbiter_tb/mapper_fifo/gate_clock
add wave -noupdate /sch_arbiter_tb/mapper_fifo/clk_gated
add wave -noupdate /sch_arbiter_tb/mapper_fifo/Pop_Pointer_CS
add wave -noupdate /sch_arbiter_tb/mapper_fifo/Pop_Pointer_NS
add wave -noupdate /sch_arbiter_tb/mapper_fifo/Push_Pointer_CS
add wave -noupdate /sch_arbiter_tb/mapper_fifo/Push_Pointer_NS
add wave -noupdate /sch_arbiter_tb/mapper_fifo/i
add wave -noupdate /sch_arbiter_tb/mapper_fifo/FIFO_REGISTERS
add wave -noupdate /sch_arbiter_tb/BankScheduler/clk
add wave -noupdate /sch_arbiter_tb/BankScheduler/rst_n
add wave -noupdate /sch_arbiter_tb/BankScheduler/ready
add wave -noupdate /sch_arbiter_tb/BankScheduler/mode
add wave -noupdate /sch_arbiter_tb/BankScheduler/valid_i
add wave -noupdate /sch_arbiter_tb/BankScheduler/dq_i
add wave -noupdate /sch_arbiter_tb/BankScheduler/idx_i
add wave -noupdate /sch_arbiter_tb/BankScheduler/ra_i
add wave -noupdate /sch_arbiter_tb/BankScheduler/ca_i
add wave -noupdate /sch_arbiter_tb/BankScheduler/t_i
add wave -noupdate /sch_arbiter_tb/BankScheduler/valid_o
add wave -noupdate /sch_arbiter_tb/BankScheduler/dq_o
add wave -noupdate /sch_arbiter_tb/BankScheduler/idx_o
add wave -noupdate /sch_arbiter_tb/BankScheduler/ra_o
add wave -noupdate /sch_arbiter_tb/BankScheduler/ca_o
add wave -noupdate /sch_arbiter_tb/BankScheduler/t_o
add wave -noupdate /sch_arbiter_tb/BankScheduler/rd_empty
add wave -noupdate /sch_arbiter_tb/BankScheduler/grant
add wave -noupdate /sch_arbiter_tb/BankScheduler/num
add wave -noupdate /sch_arbiter_tb/BankScheduler/last_ra
add wave -noupdate /sch_arbiter_tb/BankScheduler/full
add wave -noupdate /sch_arbiter_tb/BankScheduler/mid
add wave -noupdate /sch_arbiter_tb/BankScheduler/empty
add wave -noupdate /sch_arbiter_tb/BankScheduler/push
add wave -noupdate /sch_arbiter_tb/BankScheduler/burst_i
add wave -noupdate /sch_arbiter_tb/BankScheduler/selector/valid_i
add wave -noupdate /sch_arbiter_tb/BankScheduler/selector/ra_i
add wave -noupdate /sch_arbiter_tb/BankScheduler/selector/t_i
add wave -noupdate /sch_arbiter_tb/BankScheduler/selector/last_ra
add wave -noupdate /sch_arbiter_tb/BankScheduler/selector/full
add wave -noupdate /sch_arbiter_tb/BankScheduler/selector/mid
add wave -noupdate /sch_arbiter_tb/BankScheduler/selector/empty
add wave -noupdate /sch_arbiter_tb/BankScheduler/selector/rd_empty
add wave -noupdate /sch_arbiter_tb/BankScheduler/selector/rd_full
add wave -noupdate /sch_arbiter_tb/BankScheduler/selector/rd_mid
add wave -noupdate /sch_arbiter_tb/BankScheduler/selector/wr_empty
add wave -noupdate /sch_arbiter_tb/BankScheduler/selector/wr_full
add wave -noupdate /sch_arbiter_tb/BankScheduler/selector/wr_mid
add wave -noupdate /sch_arbiter_tb/BankScheduler/selector/hits
add wave -noupdate /sch_arbiter_tb/BankScheduler/selector/i
add wave -noupdate /sch_arbiter_tb/BankScheduler/selector/get_index/get_index
add wave -noupdate /sch_arbiter_tb/BankScheduler/selector/get_index/in
add wave -noupdate /sch_arbiter_tb/BankScheduler/selector/get_index/request_type
add wave -noupdate /sch_arbiter_tb/BankScheduler/selector/hot2idx/hot2idx
add wave -noupdate /sch_arbiter_tb/BankScheduler/selector/hot2idx/in
add wave -noupdate /sch_arbiter_tb/BankScheduler/counter/clk
add wave -noupdate /sch_arbiter_tb/BankScheduler/counter/rst_n
add wave -noupdate /sch_arbiter_tb/BankScheduler/counter/t_i
add wave -noupdate /sch_arbiter_tb/BankScheduler/counter/t_o
add wave -noupdate /sch_arbiter_tb/BankScheduler/counter/wr_valid
add wave -noupdate /sch_arbiter_tb/BankScheduler/counter/rd_valid
add wave -noupdate /sch_arbiter_tb/BankScheduler/counter/wr_cnt
add wave -noupdate /sch_arbiter_tb/BankScheduler/scheduler/clk
add wave -noupdate /sch_arbiter_tb/BankScheduler/scheduler/rst_n
add wave -noupdate /sch_arbiter_tb/BankScheduler/scheduler/ready
add wave -noupdate /sch_arbiter_tb/BankScheduler/scheduler/mode
add wave -noupdate /sch_arbiter_tb/BankScheduler/scheduler/burst_i
add wave -noupdate /sch_arbiter_tb/BankScheduler/scheduler/empty
add wave -noupdate /sch_arbiter_tb/BankScheduler/scheduler/pop
add wave -noupdate /sch_arbiter_tb/BankScheduler/scheduler/valid_o
add wave -noupdate /sch_arbiter_tb/BankScheduler/scheduler/rd_empty
add wave -noupdate /sch_arbiter_tb/BankScheduler/scheduler/wr_empty
add wave -noupdate /sch_arbiter_tb/BankScheduler/scheduler/hits
add wave -noupdate /sch_arbiter_tb/BankScheduler/scheduler/i
add wave -noupdate /sch_arbiter_tb/BankScheduler/scheduler/CB
add wave -noupdate /sch_arbiter_tb/BankScheduler/scheduler/NB
add wave -noupdate /sch_arbiter_tb/BankScheduler/scheduler/get_index/get_index
add wave -noupdate /sch_arbiter_tb/BankScheduler/scheduler/get_index/in
add wave -noupdate /sch_arbiter_tb/BankScheduler/scheduler/get_index/request_type
add wave -noupdate /sch_arbiter_tb/BankScheduler/scheduler/hot2idx/hot2idx
add wave -noupdate /sch_arbiter_tb/BankScheduler/scheduler/hot2idx/in
add wave -noupdate /sch_arbiter_tb/BankScheduler/bs_dp/clk
add wave -noupdate /sch_arbiter_tb/BankScheduler/bs_dp/rst_n
add wave -noupdate /sch_arbiter_tb/BankScheduler/bs_dp/push
add wave -noupdate /sch_arbiter_tb/BankScheduler/bs_dp/pop
add wave -noupdate /sch_arbiter_tb/BankScheduler/bs_dp/valid_i
add wave -noupdate /sch_arbiter_tb/BankScheduler/bs_dp/dq_i
add wave -noupdate /sch_arbiter_tb/BankScheduler/bs_dp/idx_i
add wave -noupdate /sch_arbiter_tb/BankScheduler/bs_dp/ra_i
add wave -noupdate /sch_arbiter_tb/BankScheduler/bs_dp/ca_i
add wave -noupdate /sch_arbiter_tb/BankScheduler/bs_dp/last_ra
add wave -noupdate /sch_arbiter_tb/BankScheduler/bs_dp/full
add wave -noupdate /sch_arbiter_tb/BankScheduler/bs_dp/mid
add wave -noupdate /sch_arbiter_tb/BankScheduler/bs_dp/empty
add wave -noupdate /sch_arbiter_tb/BankScheduler/bs_dp/dq_o
add wave -noupdate /sch_arbiter_tb/BankScheduler/bs_dp/idx_o
add wave -noupdate /sch_arbiter_tb/BankScheduler/bs_dp/ra_o
add wave -noupdate /sch_arbiter_tb/BankScheduler/bs_dp/ca_o
add wave -noupdate /sch_arbiter_tb/BankScheduler/bs_dp/type_o
add wave -noupdate /sch_arbiter_tb/BankScheduler/bs_dp/first_burst
add wave -noupdate /sch_arbiter_tb/BankScheduler/bs_dp/grant
add wave -noupdate /sch_arbiter_tb/BankScheduler/bs_dp/f_ca_o
add wave -noupdate /sch_arbiter_tb/BankScheduler/bs_dp/f_ra_o
add wave -noupdate /sch_arbiter_tb/BankScheduler/bs_dp/f_dq_o
add wave -noupdate /sch_arbiter_tb/BankScheduler/bs_dp/f_idx_o
add wave -noupdate /sch_arbiter_tb/BankScheduler/bs_dp/ex_sel
add wave -noupdate /sch_arbiter_tb/BankScheduler/bs_dp/grant_o
add wave -noupdate /sch_arbiter_tb/BankScheduler/bs_dp/valid_o
add wave -noupdate /sch_arbiter_tb/BankScheduler/bs_dp/i
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/clk}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/rst_n}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/data_i}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/valid_i}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/grant_o}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/last_addr}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/mid}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/data_o}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/valid_o}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/grant_i}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/CS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/NS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/gate_clock}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/clk_gated}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/Pop_Pointer_CS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/Pop_Pointer_NS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/Push_Pointer_CS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/Push_Pointer_NS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/i}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/clk}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/rst_n}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/data_i}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/valid_i}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/grant_o}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/last_addr}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/mid}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/data_o}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/valid_o}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/grant_i}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/CS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/NS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/gate_clock}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/clk_gated}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/Pop_Pointer_CS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/Pop_Pointer_NS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/Push_Pointer_CS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/Push_Pointer_NS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/i}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/clk}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/rst_n}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/data_i}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/valid_i}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/grant_o}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/last_addr}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/mid}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/data_o}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/valid_o}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/grant_i}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/CS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/NS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/gate_clock}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/clk_gated}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/Pop_Pointer_CS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/Pop_Pointer_NS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/Push_Pointer_CS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/Push_Pointer_NS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/i}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/clk}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/rst_n}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/data_i}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/valid_i}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/grant_o}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/last_addr}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/mid}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/data_o}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/valid_o}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/grant_i}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/CS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/NS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/gate_clock}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/clk_gated}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/Pop_Pointer_CS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/Pop_Pointer_NS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/Push_Pointer_CS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/Push_Pointer_NS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/i}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/clk}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/rst_n}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/data_i}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/valid_i}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/grant_o}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/last_addr}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/mid}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/data_o}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/valid_o}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/grant_i}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/CS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/NS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/gate_clock}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/clk_gated}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/Pop_Pointer_CS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/Pop_Pointer_NS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/Push_Pointer_CS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/Push_Pointer_NS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/i}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/clk}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/rst_n}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/data_i}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/valid_i}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/grant_o}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/last_addr}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/mid}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/data_o}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/valid_o}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/grant_i}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/CS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/NS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/gate_clock}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/clk_gated}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/Pop_Pointer_CS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/Pop_Pointer_NS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/Push_Pointer_CS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/Push_Pointer_NS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/i}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/clk}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/rst_n}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/data_i}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/valid_i}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/grant_o}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/last_addr}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/mid}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/data_o}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/valid_o}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/grant_i}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/CS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/NS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/gate_clock}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/clk_gated}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/Pop_Pointer_CS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/Pop_Pointer_NS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/Push_Pointer_CS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/Push_Pointer_NS}
add wave -noupdate {/sch_arbiter_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/i}
add wave -noupdate /sch_arbiter_tb/BankScheduler/bs_dp/hot2idx/hot2idx
add wave -noupdate /sch_arbiter_tb/BankScheduler/bs_dp/hot2idx/in
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {75 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 365
configure wave -valuecolwidth 129
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {50 ns} {84 ns}
