onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /cntr_bs_tb/clk
add wave -noupdate /cntr_bs_tb/rst_n
add wave -noupdate /cntr_bs_tb/ready
add wave -noupdate /cntr_bs_tb/mode
add wave -noupdate /cntr_bs_tb/dq_i
add wave -noupdate /cntr_bs_tb/idx_i
add wave -noupdate /cntr_bs_tb/ra_i
add wave -noupdate /cntr_bs_tb/ca_i
add wave -noupdate /cntr_bs_tb/t_i
add wave -noupdate /cntr_bs_tb/valid_i
add wave -noupdate /cntr_bs_tb/BankScheduler/num
add wave -noupdate /cntr_bs_tb/cntr_mode/rd_empty
add wave -noupdate /cntr_bs_tb/cntr_mode/num
add wave -noupdate /cntr_bs_tb/cntr_mode/mode
add wave -noupdate /cntr_bs_tb/BankScheduler/push
add wave -noupdate /cntr_bs_tb/BankScheduler/pop
add wave -noupdate /cntr_bs_tb/BankScheduler/bs_dp/grant
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/FIFO_REGISTERS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/FIFO_REGISTERS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/FIFO_REGISTERS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/FIFO_REGISTERS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/FIFO_REGISTERS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/FIFO_REGISTERS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/FIFO_REGISTERS}
add wave -noupdate /cntr_bs_tb/dq_o
add wave -noupdate /cntr_bs_tb/idx_o
add wave -noupdate /cntr_bs_tb/ra_o
add wave -noupdate /cntr_bs_tb/ca_o
add wave -noupdate /cntr_bs_tb/t_o
add wave -noupdate /cntr_bs_tb/num
add wave -noupdate /cntr_bs_tb/valid_o
add wave -noupdate /cntr_bs_tb/grant
add wave -noupdate /cntr_bs_tb/BankScheduler/valid_i
add wave -noupdate /cntr_bs_tb/BankScheduler/dq_i
add wave -noupdate /cntr_bs_tb/BankScheduler/idx_i
add wave -noupdate /cntr_bs_tb/BankScheduler/ra_i
add wave -noupdate /cntr_bs_tb/BankScheduler/ca_i
add wave -noupdate /cntr_bs_tb/BankScheduler/t_i
add wave -noupdate /cntr_bs_tb/BankScheduler/valid_o
add wave -noupdate /cntr_bs_tb/BankScheduler/dq_o
add wave -noupdate /cntr_bs_tb/BankScheduler/idx_o
add wave -noupdate /cntr_bs_tb/BankScheduler/ra_o
add wave -noupdate /cntr_bs_tb/BankScheduler/ca_o
add wave -noupdate /cntr_bs_tb/BankScheduler/t_o
add wave -noupdate /cntr_bs_tb/BankScheduler/grant
add wave -noupdate /cntr_bs_tb/BankScheduler/last_ra
add wave -noupdate /cntr_bs_tb/BankScheduler/full
add wave -noupdate /cntr_bs_tb/BankScheduler/mid
add wave -noupdate /cntr_bs_tb/BankScheduler/empty
add wave -noupdate /cntr_bs_tb/BankScheduler/burst_i
add wave -noupdate /cntr_bs_tb/BankScheduler/selector/valid_i
add wave -noupdate /cntr_bs_tb/BankScheduler/selector/ra_i
add wave -noupdate /cntr_bs_tb/BankScheduler/selector/t_i
add wave -noupdate /cntr_bs_tb/BankScheduler/selector/last_ra
add wave -noupdate /cntr_bs_tb/BankScheduler/selector/full
add wave -noupdate /cntr_bs_tb/BankScheduler/selector/mid
add wave -noupdate /cntr_bs_tb/BankScheduler/selector/empty
add wave -noupdate /cntr_bs_tb/BankScheduler/selector/push
add wave -noupdate /cntr_bs_tb/BankScheduler/selector/rd_empty
add wave -noupdate /cntr_bs_tb/BankScheduler/selector/rd_full
add wave -noupdate /cntr_bs_tb/BankScheduler/selector/rd_mid
add wave -noupdate /cntr_bs_tb/BankScheduler/selector/wr_empty
add wave -noupdate /cntr_bs_tb/BankScheduler/selector/wr_full
add wave -noupdate /cntr_bs_tb/BankScheduler/selector/wr_mid
add wave -noupdate /cntr_bs_tb/BankScheduler/selector/hits
add wave -noupdate /cntr_bs_tb/BankScheduler/scheduler/ready
add wave -noupdate /cntr_bs_tb/BankScheduler/scheduler/mode
add wave -noupdate /cntr_bs_tb/BankScheduler/scheduler/burst_i
add wave -noupdate /cntr_bs_tb/BankScheduler/scheduler/empty
add wave -noupdate /cntr_bs_tb/BankScheduler/scheduler/pop
add wave -noupdate /cntr_bs_tb/BankScheduler/scheduler/valid_o
add wave -noupdate /cntr_bs_tb/BankScheduler/scheduler/rd_empty
add wave -noupdate /cntr_bs_tb/BankScheduler/scheduler/wr_empty
add wave -noupdate /cntr_bs_tb/BankScheduler/scheduler/hits
add wave -noupdate /cntr_bs_tb/BankScheduler/scheduler/i
add wave -noupdate /cntr_bs_tb/BankScheduler/scheduler/CS
add wave -noupdate /cntr_bs_tb/BankScheduler/scheduler/NS
add wave -noupdate /cntr_bs_tb/BankScheduler/scheduler/CB
add wave -noupdate /cntr_bs_tb/BankScheduler/scheduler/NB
add wave -noupdate /cntr_bs_tb/BankScheduler/bs_dp/valid_i
add wave -noupdate /cntr_bs_tb/BankScheduler/bs_dp/dq_i
add wave -noupdate /cntr_bs_tb/BankScheduler/bs_dp/idx_i
add wave -noupdate /cntr_bs_tb/BankScheduler/bs_dp/ra_i
add wave -noupdate /cntr_bs_tb/BankScheduler/bs_dp/ca_i
add wave -noupdate /cntr_bs_tb/BankScheduler/bs_dp/last_ra
add wave -noupdate /cntr_bs_tb/BankScheduler/bs_dp/full
add wave -noupdate /cntr_bs_tb/BankScheduler/bs_dp/mid
add wave -noupdate /cntr_bs_tb/BankScheduler/bs_dp/empty
add wave -noupdate /cntr_bs_tb/BankScheduler/bs_dp/dq_o
add wave -noupdate /cntr_bs_tb/BankScheduler/bs_dp/idx_o
add wave -noupdate /cntr_bs_tb/BankScheduler/bs_dp/ra_o
add wave -noupdate /cntr_bs_tb/BankScheduler/bs_dp/ca_o
add wave -noupdate /cntr_bs_tb/BankScheduler/bs_dp/type_o
add wave -noupdate /cntr_bs_tb/BankScheduler/bs_dp/first_burst
add wave -noupdate /cntr_bs_tb/BankScheduler/bs_dp/f_ca_o
add wave -noupdate /cntr_bs_tb/BankScheduler/bs_dp/f_ra_o
add wave -noupdate /cntr_bs_tb/BankScheduler/bs_dp/f_dq_o
add wave -noupdate /cntr_bs_tb/BankScheduler/bs_dp/f_idx_o
add wave -noupdate /cntr_bs_tb/BankScheduler/bs_dp/ex_sel
add wave -noupdate /cntr_bs_tb/BankScheduler/bs_dp/grant_o
add wave -noupdate /cntr_bs_tb/BankScheduler/bs_dp/valid_o
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/data_i}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/valid_i}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/grant_o}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/last_addr}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/mid}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/data_o}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/valid_o}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/grant_i}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/CS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/NS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/Pop_Pointer_CS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/Pop_Pointer_NS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/Push_Pointer_CS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[6]/wr_fifo/Push_Pointer_NS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/data_i}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/valid_i}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/grant_o}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/last_addr}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/mid}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/data_o}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/valid_o}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/grant_i}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/CS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/NS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/Pop_Pointer_CS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/Pop_Pointer_NS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/Push_Pointer_CS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[5]/wr_fifo/Push_Pointer_NS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/data_i}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/valid_i}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/grant_o}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/last_addr}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/mid}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/data_o}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/valid_o}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/grant_i}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/CS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/NS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/Pop_Pointer_CS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/Pop_Pointer_NS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/Push_Pointer_CS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk2[4]/wr_fifo/Push_Pointer_NS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/data_i}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/valid_i}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/grant_o}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/last_addr}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/mid}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/data_o}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/valid_o}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/grant_i}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/CS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/NS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/Pop_Pointer_CS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/Pop_Pointer_NS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/Push_Pointer_CS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[3]/rd_fifo/Push_Pointer_NS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/data_i}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/valid_i}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/grant_o}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/last_addr}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/mid}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/data_o}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/valid_o}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/grant_i}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/CS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/NS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/Pop_Pointer_CS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/Pop_Pointer_NS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/Push_Pointer_CS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[2]/rd_fifo/Push_Pointer_NS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/data_i}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/valid_i}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/grant_o}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/last_addr}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/mid}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/data_o}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/valid_o}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/grant_i}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/CS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/NS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/Pop_Pointer_CS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/Pop_Pointer_NS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/Push_Pointer_CS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[1]/rd_fifo/Push_Pointer_NS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/data_i}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/valid_i}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/grant_o}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/last_addr}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/mid}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/data_o}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/valid_o}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/grant_i}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/CS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/NS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/Pop_Pointer_CS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/Pop_Pointer_NS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/Push_Pointer_CS}
add wave -noupdate {/cntr_bs_tb/BankScheduler/bs_dp/genblk1[0]/rd_fifo/Push_Pointer_NS}
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {8 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 367
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {28 ns} {104 ns}
