onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /cntr_bs_dp_tb/clk
add wave -noupdate /cntr_bs_dp_tb/rst_n
add wave -noupdate /cntr_bs_dp_tb/valid
add wave -noupdate /cntr_bs_dp_tb/pop
add wave -noupdate /cntr_bs_dp_tb/push
add wave -noupdate /cntr_bs_dp_tb/dq_i
add wave -noupdate /cntr_bs_dp_tb/idx_i
add wave -noupdate /cntr_bs_dp_tb/ra_i
add wave -noupdate /cntr_bs_dp_tb/ca_i
add wave -noupdate /cntr_bs_dp_tb/type_i
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[6]/wr_fifo/FIFO_REGISTERS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[5]/wr_fifo/FIFO_REGISTERS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[4]/wr_fifo/FIFO_REGISTERS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[3]/rd_fifo/FIFO_REGISTERS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[2]/rd_fifo/FIFO_REGISTERS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[1]/rd_fifo/FIFO_REGISTERS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[0]/rd_fifo/FIFO_REGISTERS}
add wave -noupdate /cntr_bs_dp_tb/full
add wave -noupdate /cntr_bs_dp_tb/mid
add wave -noupdate /cntr_bs_dp_tb/valid_o
add wave -noupdate /cntr_bs_dp_tb/empty
add wave -noupdate /cntr_bs_dp_tb/dq_o
add wave -noupdate /cntr_bs_dp_tb/idx_o
add wave -noupdate /cntr_bs_dp_tb/ra_o
add wave -noupdate /cntr_bs_dp_tb/ca_o
add wave -noupdate /cntr_bs_dp_tb/type_o
add wave -noupdate /cntr_bs_dp_tb/grant
add wave -noupdate /cntr_bs_dp_tb/last_ra
add wave -noupdate /cntr_bs_dp_tb/bs_dp/clk
add wave -noupdate /cntr_bs_dp_tb/bs_dp/rst_n
add wave -noupdate /cntr_bs_dp_tb/bs_dp/push
add wave -noupdate /cntr_bs_dp_tb/bs_dp/pop
add wave -noupdate /cntr_bs_dp_tb/bs_dp/valid_i
add wave -noupdate /cntr_bs_dp_tb/bs_dp/dq_i
add wave -noupdate /cntr_bs_dp_tb/bs_dp/idx_i
add wave -noupdate /cntr_bs_dp_tb/bs_dp/ra_i
add wave -noupdate /cntr_bs_dp_tb/bs_dp/ca_i
add wave -noupdate /cntr_bs_dp_tb/bs_dp/last_ra
add wave -noupdate /cntr_bs_dp_tb/bs_dp/full
add wave -noupdate /cntr_bs_dp_tb/bs_dp/mid
add wave -noupdate /cntr_bs_dp_tb/bs_dp/valid_o
add wave -noupdate /cntr_bs_dp_tb/bs_dp/dq_o
add wave -noupdate /cntr_bs_dp_tb/bs_dp/idx_o
add wave -noupdate /cntr_bs_dp_tb/bs_dp/ra_o
add wave -noupdate /cntr_bs_dp_tb/bs_dp/ca_o
add wave -noupdate /cntr_bs_dp_tb/bs_dp/type_o
add wave -noupdate /cntr_bs_dp_tb/bs_dp/grant
add wave -noupdate /cntr_bs_dp_tb/bs_dp/f_ca_o
add wave -noupdate /cntr_bs_dp_tb/bs_dp/f_ra_o
add wave -noupdate /cntr_bs_dp_tb/bs_dp/f_dq_o
add wave -noupdate /cntr_bs_dp_tb/bs_dp/f_idx_o
add wave -noupdate /cntr_bs_dp_tb/bs_dp/ex_sel
add wave -noupdate /cntr_bs_dp_tb/bs_dp/grant_o
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[6]/wr_fifo/data_i}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[6]/wr_fifo/valid_i}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[6]/wr_fifo/grant_o}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[6]/wr_fifo/last_addr}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[6]/wr_fifo/mid}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[6]/wr_fifo/data_o}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[6]/wr_fifo/valid_o}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[6]/wr_fifo/grant_i}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[6]/wr_fifo/CS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[6]/wr_fifo/NS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[6]/wr_fifo/Pop_Pointer_CS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[6]/wr_fifo/Pop_Pointer_NS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[6]/wr_fifo/Push_Pointer_CS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[6]/wr_fifo/Push_Pointer_NS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[5]/wr_fifo/data_i}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[5]/wr_fifo/valid_i}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[5]/wr_fifo/grant_o}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[5]/wr_fifo/last_addr}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[5]/wr_fifo/mid}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[5]/wr_fifo/data_o}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[5]/wr_fifo/valid_o}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[5]/wr_fifo/grant_i}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[5]/wr_fifo/CS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[5]/wr_fifo/NS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[5]/wr_fifo/Pop_Pointer_CS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[5]/wr_fifo/Pop_Pointer_NS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[5]/wr_fifo/Push_Pointer_CS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[5]/wr_fifo/Push_Pointer_NS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[4]/wr_fifo/data_i}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[4]/wr_fifo/valid_i}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[4]/wr_fifo/grant_o}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[4]/wr_fifo/last_addr}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[4]/wr_fifo/mid}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[4]/wr_fifo/data_o}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[4]/wr_fifo/valid_o}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[4]/wr_fifo/grant_i}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[4]/wr_fifo/CS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[4]/wr_fifo/NS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[4]/wr_fifo/Pop_Pointer_CS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[4]/wr_fifo/Pop_Pointer_NS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[4]/wr_fifo/Push_Pointer_CS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk2[4]/wr_fifo/Push_Pointer_NS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[3]/rd_fifo/data_i}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[3]/rd_fifo/valid_i}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[3]/rd_fifo/grant_o}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[3]/rd_fifo/last_addr}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[3]/rd_fifo/mid}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[3]/rd_fifo/data_o}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[3]/rd_fifo/valid_o}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[3]/rd_fifo/grant_i}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[3]/rd_fifo/CS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[3]/rd_fifo/NS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[3]/rd_fifo/gate_clock}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[3]/rd_fifo/clk_gated}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[3]/rd_fifo/Pop_Pointer_CS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[3]/rd_fifo/Pop_Pointer_NS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[3]/rd_fifo/Push_Pointer_CS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[3]/rd_fifo/Push_Pointer_NS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[2]/rd_fifo/data_i}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[2]/rd_fifo/valid_i}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[2]/rd_fifo/grant_o}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[2]/rd_fifo/last_addr}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[2]/rd_fifo/mid}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[2]/rd_fifo/data_o}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[2]/rd_fifo/valid_o}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[2]/rd_fifo/grant_i}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[2]/rd_fifo/CS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[2]/rd_fifo/NS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[2]/rd_fifo/Pop_Pointer_CS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[2]/rd_fifo/Pop_Pointer_NS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[2]/rd_fifo/Push_Pointer_CS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[2]/rd_fifo/Push_Pointer_NS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[1]/rd_fifo/data_i}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[1]/rd_fifo/valid_i}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[1]/rd_fifo/grant_o}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[1]/rd_fifo/last_addr}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[1]/rd_fifo/mid}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[1]/rd_fifo/data_o}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[1]/rd_fifo/valid_o}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[1]/rd_fifo/grant_i}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[1]/rd_fifo/CS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[1]/rd_fifo/NS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[1]/rd_fifo/Pop_Pointer_CS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[1]/rd_fifo/Pop_Pointer_NS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[1]/rd_fifo/Push_Pointer_CS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[1]/rd_fifo/Push_Pointer_NS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[0]/rd_fifo/data_i}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[0]/rd_fifo/valid_i}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[0]/rd_fifo/grant_o}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[0]/rd_fifo/last_addr}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[0]/rd_fifo/mid}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[0]/rd_fifo/data_o}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[0]/rd_fifo/valid_o}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[0]/rd_fifo/grant_i}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[0]/rd_fifo/CS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[0]/rd_fifo/NS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[0]/rd_fifo/Pop_Pointer_CS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[0]/rd_fifo/Pop_Pointer_NS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[0]/rd_fifo/Push_Pointer_CS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[0]/rd_fifo/Push_Pointer_NS}
add wave -noupdate {/cntr_bs_dp_tb/bs_dp/genblk1[0]/rd_fifo/i}
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {47 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 363
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ns} {107 ns}
