onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/clk
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/rst_n
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/valid_i
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/data_i
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/idx_i
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/row_i
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/col_i
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/t_i
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/ready
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/returner_valid
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/returner_type
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/returner_data
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/returner_index
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/CS_n
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/CA
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/CAI
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/DM_n
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/DQ
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/DQS_t
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/DQS_c
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/ALERT_n
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/data_o
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/idx_o
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/row_o
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/col_o
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/t_o
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/ba_o
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/bg_o
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/wr_en
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/burst_state
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/burst_type
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/burst_address_bank
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/burst_address_bg
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/burst_address_row
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/burst_cmd_o
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/cmd_index_o
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/start_new_burst
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/clk
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/rst_n
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/in_valid
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/in_request_type
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/in_request_data
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/in_request_address
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/out_busy
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/request_done_valid
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/the_type
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/data_in
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/index
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/write_done
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/read_done
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/data_out
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/ready
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/valid_o
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/dq_o
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/idx_o
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/ra_o
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/ca_o
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/t_o
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/request_out
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/out_index
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/grant_o
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/bank_out_valid
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/pop
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/valid_out
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/out_fifo_sch
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/idx_out
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/num
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/mode
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/rd_empty
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {45 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 399
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ns} {65 ns}
