onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/clk
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/rst_n
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/valid_i
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/data_i
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/idx_i
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/row_i
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/col_i
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/t_i
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/ready
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/returner_valid
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/returner_type
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/returner_data
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/returner_index
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/CS_n
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/CA
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/CAI
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/DM_n
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/DQ
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/DQS_t
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/DQS_c
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/ALERT_n
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/data_o
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/idx_o
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/row_o
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/col_o
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/t_o
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/ba_o
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/bg_o
add wave -noupdate -color Magenta -itemcolor Magenta /the_optimum_tb/the_memory_controller/the_back_end/wr_en
add wave -noupdate -color Gold -itemcolor Gold /the_optimum_tb/the_memory_controller/the_back_end/the_handler/arbiter_type_temp
add wave -noupdate -color Gold -itemcolor Gold /the_optimum_tb/the_memory_controller/the_back_end/burst_state
add wave -noupdate -color Gold -itemcolor Gold /the_optimum_tb/the_memory_controller/the_front_end/t_o
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_front_end/genblk1[0]/BankScheduler/t_o}
add wave -noupdate -color Gold /the_optimum_tb/the_memory_controller/the_back_end/burst_type
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/valid_o
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/burst_address_bank
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/burst_address_bg
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/burst_address_row
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/burst_cmd_o
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/cmd_index_o
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/start_new_burst
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/clk
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/rst_n
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/in_valid
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/in_request_type
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/in_request_data
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/in_request_address
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/out_busy
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/request_done_valid
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/the_type
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/data_in
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/index
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/write_done
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/read_done
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/data_out
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/ready
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/dq_o
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/idx_o
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/ra_o
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/ca_o
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/request_out
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/out_index
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/grant_o
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/bank_out_valid
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/pop
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/valid_out
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/out_fifo_sch
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/idx_out
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/num
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/mode
add wave -noupdate /the_optimum_tb/the_memory_controller/the_front_end/rd_empty
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/clk
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/rst_n
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/out_burst_state
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/out_burst_type
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/out_burst_address_bank
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/out_burst_address_bg
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/out_burst_address_row
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/in_burst_cmd
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/in_cmd_index
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/start_new_burst
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/arbiter_valid
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/in_req_address
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/arbiter_data
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/arbiter_index
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/CS_n
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/CA
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/CAI
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/DM_n
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/DQ
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/DQS_t
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/DQS_c
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/ALERT_n
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/returner_valid
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/returner_type
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/returner_data
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/returner_index
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/DQ_logic
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/DQS_t_logic
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/DQS_c_logic
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/ALERT_n_logic
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/burst
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/new_burst_counter
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/in_burst
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/older_in_burst
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/out_burst
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/new_burst_flag
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/return_req
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/burst_data_counter
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/first_one_in_mask
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/first_one_id
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/data_wait_counter
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/cmd_burst_id
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/cmd_to_send
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/empty_bursts_counter
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/the_handler/arbiter_type
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_front_end/genblk1[0]/BankScheduler/clk}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_front_end/genblk1[0]/BankScheduler/rst_n}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_front_end/genblk1[0]/BankScheduler/ready}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_front_end/genblk1[0]/BankScheduler/mode}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_front_end/genblk1[0]/BankScheduler/valid_i}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_front_end/genblk1[0]/BankScheduler/dq_i}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_front_end/genblk1[0]/BankScheduler/idx_i}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_front_end/genblk1[0]/BankScheduler/ra_i}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_front_end/genblk1[0]/BankScheduler/ca_i}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_front_end/genblk1[0]/BankScheduler/valid_o}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_front_end/genblk1[0]/BankScheduler/dq_o}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_front_end/genblk1[0]/BankScheduler/idx_o}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_front_end/genblk1[0]/BankScheduler/ra_o}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_front_end/genblk1[0]/BankScheduler/ca_o}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_front_end/genblk1[0]/BankScheduler/rd_empty}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_front_end/genblk1[0]/BankScheduler/grant}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_front_end/genblk1[0]/BankScheduler/num}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_front_end/genblk1[0]/BankScheduler/last_ra}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_front_end/genblk1[0]/BankScheduler/full}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_front_end/genblk1[0]/BankScheduler/mid}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_front_end/genblk1[0]/BankScheduler/empty}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_front_end/genblk1[0]/BankScheduler/push}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_front_end/genblk1[0]/BankScheduler/pop}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_front_end/genblk1[0]/BankScheduler/burst_i}
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/arbiter/Bank_Groups/clk
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/arbiter/Bank_Groups/rst_n
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/arbiter/Bank_Groups/flag
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/arbiter/Bank_Groups/Req
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/arbiter/Bank_Groups/Done
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/arbiter/Bank_Groups/Start_A
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/arbiter/Bank_Groups/Start_B
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/arbiter/Bank_Groups/Start_C
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/arbiter/Bank_Groups/Start_D
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/arbiter/Bank_Groups/sel
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/arbiter/Bank_Groups/ReqD
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/arbiter/Bank_Groups/ReqC
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/arbiter/Bank_Groups/ReqB
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/arbiter/Bank_Groups/ReqA
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/arbiter/Bank_Groups/Done_D
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/arbiter/Bank_Groups/Done_C
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/arbiter/Bank_Groups/Done_B
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/arbiter/Bank_Groups/Done_A
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/arbiter/Bank_Groups/CS
add wave -noupdate /the_optimum_tb/the_memory_controller/the_back_end/arbiter/Bank_Groups/NS
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[0]/Bank/clk}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[0]/Bank/rst_n}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[0]/Bank/start}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[0]/Bank/Valid}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[0]/Bank/Ready_A}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[0]/Bank/Ready_B}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[0]/Bank/Ready_C}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[0]/Bank/Ready_D}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[0]/Bank/sel}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[0]/Bank/en}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[0]/Bank/done}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[0]/Bank/Req}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[0]/Bank/valid_D}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[0]/Bank/valid_C}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[0]/Bank/valid_B}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[0]/Bank/valid_A}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[0]/Bank/CS}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[0]/Bank/NS}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[1]/Bank/clk}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[1]/Bank/rst_n}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[1]/Bank/start}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[1]/Bank/Valid}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[1]/Bank/Ready_A}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[1]/Bank/Ready_B}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[1]/Bank/Ready_C}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[1]/Bank/Ready_D}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[1]/Bank/sel}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[1]/Bank/en}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[1]/Bank/done}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[1]/Bank/Req}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[1]/Bank/valid_D}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[1]/Bank/valid_C}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[1]/Bank/valid_B}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[1]/Bank/valid_A}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[1]/Bank/CS}
add wave -noupdate {/the_optimum_tb/the_memory_controller/the_back_end/arbiter/genblk1[1]/Bank/NS}
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {48 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 516
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {15 ns} {72 ns}
